name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-matrix:
    name: Node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Tests
        run: yarn jest test/

      - name: Build
        run: yarn build

